### ISSUE TITLE
missing new line when iteration is over

### ISSUE THREAD

**Issue by CarloLucibello** [cloud-oak/ProgressBars.jl#10]
ProgressBars.jl is not reproducing exactly the behavior of tqdm. In particular, after iteration, is over, the cursor remains at the end of the line, which is very annoying if you wan to print something else or you want to produce another progress bar.

Here is an example comparison between the python and the julia behavior:
```python
# test.py
import tqdm
import time
for i in tqdm.tqdm(range(10)):
    time.sleep(0.1) 
for i in tqdm.tqdm(range(10)):
    time.sleep(0.1)
```
```julia
using ProgressBars
for i in tqdm(1:10)
    sleep(0.1)
end
for i in tqdm(1:10)
    sleep(0.1)
end
```
```
[carlo@x1 ~]$ python test.py 
100%|█████████████████████████████| 10/10 [00:01<00:00,  9.97it/s]
100%|█████████████████████████████| 10/10 [00:01<00:00,  9.97it/s]
```
```
[carlo@x1 ~]$ julia test.jl 
100.00%┣█████████████████████████┫ 10/10 00:01<00:00, 8.86 it/s][carlo@x1 ~]$ 
```

**Comment by cloud-oak** [comment]
Hi Carlo, thanks for the bug report!

You're right, that is very annoying.
I myself mostly used this package for interactive julia sessions and notebooks, so I've never noticed it before... Should be fixed by #11.

Cheers,
Konrad

**Comment by cloud-oak** [comment]
@JuliaRegistrator register

**Comment by CarloLucibello** [comment]
thanks for the quick fix!
