### ISSUE TITLE
Threads compatibility

### ISSUE THREAD

**Issue by mileslucas** [cloud-oak/ProgressBars.jl#13]
The new Julia 1.3 `Threads.@threads` macro does not work with `ProgressBar`

MWE:
```julia
using ProgressBars
a = []
Threads.@threads for i in ProgressBar(1:1000)
    push!(a, rand())
end
```

Python's tqdm figured out a way to show progress on multiple processes by showing a stack of progress bars for each process. Perhaps a similar interface could work here?

**Comment by cloud-oak** [comment]
Hi Miles, thanks for raising this issue. The [multi_threading](/cloud-oak/ProgressBars.jl/tree/multi_threading) branch contains a possible fix for this.

Could you try if it works in your case?

Cheers,
Konrad
