### ISSUE TITLE
Fails on Julia master (1.4)

### ISSUE THREAD

**Issue by KristofferC** [cloud-oak/ProgressBars.jl#16]
Julia has tweaked a bit how the `@threads` macro is lowered (https://github.com/JuliaLang/julia/pull/33396).

This means that the trick at

https://github.com/cloud-oak/ProgressBars.jl/blob/9efb51a252708968e9b36b711842e29e95df04a2/src/ProgressBars.jl#L169-L187

no longer works.

**Comment by JeffBezanson** [comment]
I recommend defining `getindex` and `firstindex` instead.

**Comment by cloud-oak** [comment]
Thanks for raising the issue and the helpful pointers towards `getindex` and `firstindex`!
PR #17 fixes this.

Cheers,
Konrad
