### ISSUE TITLE
missing set_postfix from tqdm

### ISSUE THREAD

**Issue by CarloLucibello** [cloud-oak/ProgressBars.jl#20]
To write information at the end of the progress bar

**Comment by cloud-oak** [comment]
Hi Carlo, my computer was broken so it took a while... But here goes #23 enabling the set_postfix feature, analogous to the tqdm equivalent. I'll tag a new release so it should go live on the Julia Package registry soon.

**Comment by CarloLucibello** [comment]
thanks!
