### ISSUE TITLE
Fails when # of iteration is 1

### ISSUE THREAD

**Issue by uchiiii** [cloud-oak/ProgressBars.jl#26]
Hi! Thank you for developing this useful tool.

I am currently using `ProgressBar()` function.

## Expect
It should work even when # of iteration is just 1.

## Current
When # of iteration is 1, you get the error below. 
![Screen Shot 2020-11-13 at 14 42 34](https://user-images.githubusercontent.com/32426869/99033582-93e1e100-25be-11eb-9a4b-2cd3ea9f1a95.png)

I believe that it would be much better to handle the corner case(# of iteration is 1) even though this tool is often used with a large number of iteration.

Thank you!

**Comment by khdlr** [comment]
Thanks for raising this issue. That definitely should not happen!

Looks like it's dividing by 0 somewhere... I'll have a look at it :)

**Comment by uchiiii** [comment]
Thank you for trying to fix the problem !

I guess some variables are `NaN` not divided by 0, because when you divide some scalar by 0 you get `Inf` like below.
![Screen Shot 2020-11-24 at 17 21 00](https://user-images.githubusercontent.com/32426869/100067413-94f5f680-2e79-11eb-9cd6-33743c778db6.png)

But I am not sure exactly where there is a bug....

**Comment by uchiiii** [comment]
How about putting these on [here](https://github.com/cloud-oak/ProgressBars.jl/blob/2b22490e773aa8fa41a08aea46b9660b0ca4ab1c/src/ProgressBars.jl#L123)
```julia
    if isnan(ETA) || isinf(ETA)
      ETA = t.total - t.current        
    end 
```

**Comment by khdlr** [comment]
Interestingly, the behaviour when dividing by 0 is different for `0 / 0`:
```julia
julia> 0 / 0
NaN

julia> 10 / 0
Inf
```

**Comment by khdlr** [comment]
Thanks for diving into this issue, and sorry that it took so long for me to get around it. #28 is more of a temporary fix until I understand why the library doesn't do what it's supposed to do in this case... :smile:
