### ISSUE TITLE
Multi-line postfix?

### ISSUE THREAD

**Issue by MilesCranmer** [cloud-oak/ProgressBars.jl#33]
Hi,

Great package. Is there any way I can get multi-line postfix working? I'm trying to figure this out myself, but if you've got any pointers, I'd appreciate advice!

I'm trying to get ProgressBars.jl implemented in [SymbolicRegression.jl](https://github.com/MilesCranmer/SymbolicRegression.jl/). Every iteration, one updates a list of equations and prints these to the terminal. Would be really nice to "refresh" this list somehow.

Example:

```julia
iter=ProgressBar(1:10)
for i in iter
    sleep(0.1)
    set_postfix(iter, Out=@sprintf("Testing\nTest 1\nTest 2"))
end
```
<img width="550" alt="Screen Shot 2021-02-23 at 7 24 14 PM" src="https://user-images.githubusercontent.com/7593028/108926591-b8614680-760c-11eb-9d64-e6e321d009b2.png">

I guess I need to add something to take a "lines" argument to the postfix, and those lines are erased using one of these commands? https://stackoverflow.com/a/53820485/2689923

Cheers,
Miles

**Comment by MilesCranmer** [comment]
Another hack would be to just use the current console width to calculate the required # of spaces to get to a newline. That might be cleaner. But then I guess I need to pass `ProgressBar` the width manually?

**Comment by MilesCranmer** [comment]
Got it working! It's a combination of the above two ideas. It measures the number of extra lines in the print statement, and then goes through and erases them before the next print. Let me know if you want a PR. It now allows you to add any multi-line string, e.g., `set_multiline_postfix(iter, "Test1\nTest2")` and this will get refreshed every iteration.

Here's my use-case, which now works:
<img width="938" alt="Screen Shot 2021-02-24 at 1 09 33 AM" src="https://user-images.githubusercontent.com/7593028/108955942-f6765e80-763c-11eb-818e-12a689d737a8.png">

It can print a variably-sized list of these equations, and then refresh them each iteration along with the progress bar. The normal postfix should work still too.

Here's the git diff:
```julia
diff --git a/src/ProgressBars.jl b/src/ProgressBars.jl
index 15588ae..5a760ea 100644
--- a/src/ProgressBars.jl
+++ b/src/ProgressBars.jl
@@ -42,6 +43,8 @@ mutable struct ProgressBar
     last_print::UInt
     description::AbstractString
     postfix::NamedTuple
+    extra_lines::Int
+    multilinepostfix::AbstractString
     mutex::Threads.SpinLock
 
     function ProgressBar(wrapped::Any; total::Int = -2, width = displaysize(stdout)[2], leave=true)
@@ -53,6 +56,8 @@ mutable struct ProgressBar
         this.last_print = this.start_time - 2 * PRINTING_DELAY
         this.description = ""
         this.postfix = NamedTuple()
+        this.multilinepostfix = ""
+        this.extra_lines = 0
         this.mutex = Threads.SpinLock()
         this.current = 0
 
@@ -107,13 +112,18 @@ function display_progress(t::ProgressBar)
     postfix_string = postfix_repr(t.postfix)
 
     # Reset Cursor to beginning of the line
-    print("\r")
+    for line in 1:t.extra_lines
+        move_up_1_line()
+    end
+    go_to_start_of_line()
+
 
     if t.description != ""
         barwidth -= length(t.description) + 1
         print(t.description * " ")
     end
 
+
     if (t.total <= 0)
         status_string = "$(t.current)it $elapsed [$iterations_per_second$postfix_string]"
         barwidth -= length(status_string) + 1
@@ -153,12 +163,28 @@ function display_progress(t::ProgressBar)
         print("┫ ")
         print(status_string)
     end
+    multiline_postfix_string = newline_to_spaces(t.multilinepostfix, t.width)
+    t.extra_lines = ceil(Int, length(multiline_postfix_string) / t.width)
+    print(multiline_postfix_string)
+end
+
+
+erase_to_end_of_line() = print("\033[K")
+move_up_1_line() = print("\033[1A")
+go_to_start_of_line() = print("\r")
+erase_line() = begin
+    go_to_start_of_line()
+    erase_to_end_of_line()
 end
 
 # Clear the progress bar
 function clear_progress(t::ProgressBar)
     # Reset cursor, fill width with empty spaces, and then reset again
-    print("\r", " "^t.width, "\r")
+    for line in 1:(t.extra_lines)
+        erase_line()
+        move_up_1_line()
+    end
+    erase_line()
 end
 
 function set_description(t::ProgressBar, description::AbstractString)
@@ -169,11 +195,23 @@ function set_postfix(t::ProgressBar; postfix...)
     t.postfix = values(postfix)
 end
 
+function set_multiline_postfix(t::ProgressBar, postfix::AbstractString)
+    mistakenly_used_newline_at_start = postfix[1] == '\n' && length(postfix) > 1
+    if mistakenly_used_newline_at_start
+        postfix = postfix[2:end]
+    end
+    t.multilinepostfix = postfix
+end
+
 function postfix_repr(postfix::NamedTuple)::AbstractString
     return join(map(tpl -> ", $(tpl[1]): $(tpl[2])", zip(keys(postfix), postfix)))
 end
 
 function Base.iterate(iter::ProgressBar)
+    if displaysize(stdout)[2] != iter.width
+        iter.width = displaysize(stdout)[2]
+        print("\n"^(iter.extra_lines + 2))
+    end
     iter.start_time = time_ns() - PRINTING_DELAY
     iter.current = 0
     display_progress(iter)
@@ -181,6 +219,10 @@ function Base.iterate(iter::ProgressBar)
 end
 
 function Base.iterate(iter::ProgressBar,s)
+    if displaysize(stdout)[2] != iter.width
+        iter.width = displaysize(stdout)[2]
+        print("\n"^(iter.extra_lines + 2))
+    end
     iter.current += 1
     if(time_ns() - iter.last_print > PRINTING_DELAY)
         display_progress(iter)
@@ -263,4 +305,23 @@ function Base.getindex(iter::ProgressBar, index::Int64)
     return item
 end
 
+function newline_to_spaces(string, terminal_width)
+    new_string = ""
+    width_cumulator = 0
+    for c in string
+        if c == '\n'
+            spaces_required = terminal_width - width_cumulator
+            new_string *= " "^spaces_required
+            width_cumulator = 0
+        else
+            new_string *= c
+            width_cumulator += 1
+        end
+        if width_cumulator == terminal_width
+            width_cumulator = 0
+        end
+    end
+    return new_string
+end
+
 end # module
```

I also added functionality where `ProgressBar.width` will get updated upon a terminal resize, and if this happens, a few newlines will be added. This results in a clean progress bar even with a resized terminal, like so:

<img width="1261" alt="Screen Shot 2021-02-24 at 1 02 09 AM" src="https://user-images.githubusercontent.com/7593028/108955307-edd15880-763b-11eb-8458-72a570604f2a.png">

So, when I resize the terminal, it prints a few newlines to clear space, and then recomputes `t.width`. To do this, i added the following snippet to `Base.iterate(iter::ProgressBar, s)`:
```julia
    if displaysize(stdout)[2] != iter.width
        iter.width = displaysize(stdout)[2]
        print("\n"^(iter.extra_lines + 2))
    end
```

**Comment by khdlr** [comment]
Hi Miles, that's some very cool functionality that you've added!

I've been meaning to implement the dynamic resizing part myself for quite some time now, but never got around to it. Please do consider submitting this as a PR, I think it would be very helpful for others as well.

Just to confirm that I understand correctly, is it possible to use `postfix` and `multiline_postfix` together, in a layout like this?

```
[.. ProgBar..]<postfix>
<multiline_postfix_ln1>
<multiline_postfix_ln2>
<multiline_postfix_ln3>
```

**Comment by MilesCranmer** [comment]
Thanks, I will submit a PR!

Yes; that layout will work. The changes are mostly around the existing functionality, rather than internal to it. So it shouldn't affect existing stuff.

I also recently added an argument to fix the terminal size, in case the user passes an explicit width at the start, so it won't dynamically adjust in that case, which I think would be expected.

**Comment by MilesCranmer** [comment]
Moving to #34 and #35 :)
