### ISSUE TITLE
Show s/it instead of it/s when each iteration takes a while?

### ISSUE THREAD

**Issue by rjrosati** [cloud-oak/ProgressBars.jl#36]
I was thinking it might be nice to show e.g. `11.0 s/it` instead of `0.1 it/s` when the iterations are slower than 1 per second.
This could give users more sig figs and is a little nicer to read. I'm happy to submit a PR.

**Comment by khdlr** [comment]
Hi Robbie, that's a lovely idea, feel free to submit a PR if you'd like to contribute. Otherwise I'll see to it over the next couple of days.

Cheers, Konrad
