### ISSUE TITLE
Enable customization of units

### ISSUE THREAD

**Issue by jabortell** [cloud-oak/ProgressBars.jl#39]
It appears that the unit is hard coded to `it/s`. It would be super to be able to specify one's own units, as in `tqdm`.

https://github.com/cloud-oak/ProgressBars.jl/blob/3ee98895751538704f6d10e0da6a63c617b0d0d3/src/ProgressBars.jl#L114

**Comment by khdlr** [comment]
Hi Jacob, this is implemented as of #40/[v1.1](https://github.com/cloud-oak/ProgressBars.jl/releases/tag/v1.1.0). Sorry I forgot to update the issue here until now!
