### ISSUE TITLE
`unit_scale` argument

### ISSUE THREAD

**Issue by liurui39660** [cloud-oak/ProgressBars.jl#43]
Python's `tqdm` has an `unit_scale`, it adds units to numbers, e.g. `4699189/7948748` becomes `4.69M/7.94M`. This makes it more readable.

Its documentation says
> unit_scale: bool or int or float, optional
    If 1 or True, the number of iterations will be printed with an appropriate SI metric prefix (k = 10^3, M = 10^6, etc.) [default: False]. If any other non-zero number, will scale `total` and `n`.

**Comment by khdlr** [comment]
Hi there, this one took me a while to complete. It is now included in [v.1.3.0](https://github.com/cloud-oak/ProgressBars.jl/releases/tag/v1.3.0), so feel free to try it out :)

For now the `unit_scale` argument only supports `true` or `false` to scale by kilo, mega, and giga prefixes.
