### ISSUE TITLE
ProgressBars.jl prints to stdout (tqdm et al. print to stderr)

### ISSUE THREAD

**Issue by InnovativeInventor** [cloud-oak/ProgressBars.jl#46]
The default (and only) behavior for ProgressBars.jl is to print to stdout, where it should print to stderr to be in-line with `tqdm` and similar tools. When using this wonderful library in a standard script, it is hard to pipe/parse stdout when a progress bar keeps on being written to it.

The `tqdm` documentation itself notes:
> Perhaps the most wonderful use of tqdm is in a script or on the command line. Simply inserting tqdm (or python -m tqdm) between pipes will pass through all stdin to stdout while printing progress to stderr.

Additionally, the GNU C Library [notes](https://www.gnu.org/software/libc/manual/html_node/Standard-Streams.html) that `stdout` is for "which is used for normal output from the program" whereas `stdin` is for "for error messages and diagnostics issued by the program." Various other [sources](https://pubs.opengroup.org/onlinepubs/9699919799/functions/stderr.html) concur.

I'd be happy to work on a PR to change this behavior if people agree! Thanks for maintaining this awesome library!

**Comment by khdlr** [comment]
100% agreed. This was an oversight when I put together the library (it started as a quick utility package that I threw together when I was forced to write my BSc thesis in julia :smile:). Back then I didn't care much about such issues, so the problem persists to this day.

It would be a great help if you could prepare a PR for this - maybe we can even make it configurable with an `output_stream` argument that defaults to `Base.stderr`, but the user can still supply `Base.stdout` if for some reason they really want the progress bar to appear on stdout.

**Comment by InnovativeInventor** [comment]
Great, I've made a pull request that's ready for your review!
