### ISSUE TITLE
Trunc InexactError issue during Github Actions CI Tests

### ISSUE THREAD

**Issue by JackKenney** [cloud-oak/ProgressBars.jl#50]
I'm having an issue running tests in GithubActions CI, specifically with the `julia-actions/julia-runtest@v1` routine. I'm getting this issue with a long to Int32 conversion somewhere in the ProgressBars code, but this works fine locally, so I'm not sure what the difference is.

Is this something anyone can reproduce?

```
Got exception outside of a @test
  InexactError: trunc(UInt32, 3[340](https://github.com/USER/PACKAGE/runs/RUN_NUMBER?check_suite_focus=true#step:5:340)29064562)
  Stacktrace:
    [1] throw_inexacterror(f::Symbol, #unused#::Type{UInt32}, val::UInt64)
      @ Core ./boot.jl:612
    [2] checked_trunc_uint
      @ ./boot.jl:642 [inlined]
    [3] toUInt32
      @ ./boot.jl:731 [inlined]
    [4] UInt32
      @ ./boot.jl:766 [inlined]
    [5] convert
      @ ./number.jl:7 [inlined]
    [6] setproperty!
      @ ./Base.jl:43 [inlined]
    [7] ProgressBars.ProgressBar(wrapped::UnitRange{Int32}; total::Int32, width::Nothing, leave::Bool, unit::String, unit_scale::Bool, printing_delay::Float64, output_stream::IOContext{Base.PipeEndpoint})
      @ ProgressBars ~/.julia/packages/ProgressBars/oUCdd/src/ProgressBars.jl:72
    [8] ProgressBars.ProgressBar(wrapped::UnitRange{Int32})
      @ ProgressBars ~/.julia/packages/ProgressBars/oUCdd/src/ProgressBars.jl:61
```

Workaround:

For people also experiencing it, I used the `Mocking.jl` packages to overwrite calls to tqdm with a simple return:

```
Mocking.activate()
patch = @patch ProgressBars.tqdm(x) = x

apply(patch) do
    # include all tests here
    ...
end
```

**Comment by khdlr** [comment]
Hi Jack, the stack trace points to the line where the progress bar records is start time and stores it in a `UInt` variable. My best guess would be that the failing CI test is running on a 32 bit system, and thus tries to store the timestamp (which is in the order of 2^44) into a `UInt32`.

I'll work on a fix :)

**Comment by khdlr** [comment]
Could you bump your dependency to ProgressBars v1.4.1 and see whether that fixes the problem?

**Comment by JackKenney** [comment]
Yep that fixed it! Thanks so much.

**Comment by khdlr** [comment]
Nice! It's scary how easy it is to forget about the implications of default integer widths on 32bit vs 64bit... :sweat_smile:
