### ISSUE TITLE
While multithreading, progress bar does not complete to 100%

### ISSUE THREAD

**Issue by odunbar** [cloud-oak/ProgressBars.jl#53]
First, thanks for the package!

I was glad to find something that will track progress with multithreading in a simple way. 
### Issue 
Occurs in `Julia 1.8.2`, in a completely communication free loop. Multithreading over 28 threads.
called with 
```julia
Threads.@threads for i in ProgressBar(1:N)
    ...
end
```
I've noticed the print statements complete at ~99.X% rather than the full 100% even after the calculations in the threaded loop finishes - this seems to occur every time.
<img src="https://user-images.githubusercontent.com/47412152/215908647-9e7b28b0-1885-402d-90b3-76e89bdb4ba3.png" width=300> .......... <img src="https://user-images.githubusercontent.com/47412152/215908649-85f0166e-62a9-4299-954e-ee1fa27558e6.png" width=381>

**Comment by el-oso** [comment]
Oh, I thought that I was the only one with that problem.

**Comment by khdlr** [comment]
Should be fixed in v1.5.0 now (e990ab66d2e65376a90d6ae154cb4390fbe08eca)
